### PR TITLE
feat!: show expected and actual type for mismatches

### PR DESCRIPTION
**Pull request by brprice**
Mismatches, aka non-empty holes, now show both relevant types. Previously one would see the expected type in the "Selection info" of the hole, and the actual type in the info of the body of the hole. Now one sees both in the info of the hole.

BREAKING CHANGE: the API is different from the previous backend pin. Thus this version of the frontend cannot talk to the previous version of the backend and vice versa.

### CODE REVIEW

**Comment by brprice** [comment]
There is some bug with react flow and trying to show two flows in the "same place".

To see this, create a program with a mismatch; click the mismatch and see two types in the info (you will have to scroll); now click some other node and everything breaks weirdly.

**Comment by brprice** [comment]
Note that the backend PR is https://github.com/hackworthltd/primer/pull/1172, which is not quite ready to merge currently

**Comment by brprice** [comment]
> After a bit of testing, there is one weird little quirk where the Expected Type isn't properly centered in its subview the first time you select a misfit, but it seems to go away upon subsequent selections. Per paragraph above, since this will all be restyled soon anyway, let's just leave it.

Huh, odd. I have no idea why or how that happens. I'm happy to leave it for now.

**Comment by brprice** [comment]
I have bumped this to the latest backend version (which is merged to main).

**Comment by dhess** [comment]
Is this ready to merge, then?

**Comment by brprice** [comment]
> Is this ready to merge, then?

Other than the storybook diff. It seems there are subtle changes in one of the avatars, and I don't understand why. Feel free to merge if you think this is not a worry, otherwise I could investigate.

**Comment by dhess** [comment]
Hmm, that's odd, but I'm not concerned about it. We don't properly keep Chromatic's baselines up-to-date, so it might be due to unrelated changes in dependencies.

**Pull request merged**
