### PR TITLE
feat: add support for pattern wildcards

### PR DESCRIPTION
**Pull request by dhess**
Note: only the final commit in the sequence is new. The rest is from #955, which is currently waiting for review before being merged.

### CODE REVIEW

**Comment by dhess** [comment]
My comments on how this feature currently works. This isn't a review as such; I just want to get my thoughts down so we can return to these comments and ideas for later work, and maybe hash some of these ideas out here in the PR discussion.

### `match` action now defaults to only adding the wildcard

(For posterity, before this PR, the `match` action would automatically create a pattern for each constructor in the subject's type, for non-primitive types, anyway.)

For primitives, this behavior makes sense as the default, for obvious reasons.

For non-primitives, I'm not sure. Perhaps the default behavior should depend on the level: in beginner mode, wildcard patterns may be more confusing than helpful and I wonder if we should stick to our "explicit is better than implicit" design principle.

At intermediate and expert levels, I think it would make sense to offer 2 different `match` actions: one that splats out all explicit constructors, and one that creates only the wildcard pattern.

### The output value of a newly-added branch

It appears that if one of the existing branches is the wildcard pattern, then when adding a new branch, the new branch's output will be automatically assigned to whatever the output value of the wildcard pattern is.

I'm of two minds on this. On the one hand, it's a nice touch, and it makes sense that if *any* output value is automatically assigned, it should be the wildcard's output value, because this preserves the behavior of the `match` expression. But on the other hand:

* There's a case to be made that the default output value (if any) should *not* be the same as the wildcard output value, since presumably the whole point of creating a new branch case is to distinguish it from the default (wildcard) case.
* I wonder if beginners, at least, might be confused by the fact that the new branch has any output value at all other than hole (`?`). Would they jump to the conclusion that it can't be changed, because it was pre-populated? 
* Would it lead to more program errors? Students might not notice that the automatically-provided output value is not what they want.


### The wildcard pattern visual

Personally I really like the visual style of the wildcard pattern as it's implemented here, modulo some tweaking and perhaps a different choice of wildcard symbol. I think @georgefst might be less sold on it, though. My concern with using an empty pattern var box is that students may see it and think their program is incomplete. I like the idea of using the pattern var box, but I think we would need to fill it with some symbol, and then the issue is, what symbol to use? We don't want to pick a Unicode character that could also be used for a pattern variable name, but we also don't want to reserve any of those characters as special, so it seems like a catch-22.

### The add/remove UX

I think that offering the add/remove branch options when the `match` node is selected makes sense, but it does seem to lack some discoverability. (It wasn't obvious to me on first use how to add/remove branches.) Then again, it should be easy to remember and get used to once you've discovered it, and it does seem like a natural action to offer for selected `match` nodes.

It's obviously out of scope for this PR, but I think we could do more. For example, you should be able to select a pattern box and be offered actions either to a) delete it or b) convert it to (or merge it into an existing) the wildcard pattern. It might also make sense to offer the "add a branch" whenever any pattern box is selected, though that might not work well once we have support for "deep" patterns.

This is probably also a case where adding hotkey support for add (e.g., `+`) and delete (e.g., `del`) would be helpful.

**Comment by dhess** [comment]
For posterity, another idea I had for the wildcard symbol is to use the funnel icon from https://heroicons.com. The nice thing about using an SVG is that it can't conflict with any Unicode code point. Our current choice 🤷🏽‍♀️ could, though we render it without the usual value constructor node chrome, so at least it would be somewhat distinguishable from a value constructor of the same "name." On the other hand, the funnel icon is rather abstract and not particularly obvious (to me, anyway), and we'd need to do some extra work to our node styling code to support rendering Hero Icons, I think.

**Comment by dhess** [comment]
For the record, I can reproduce similar behavior in this PR to what @brprice describes here in the earlier PR : https://github.com/hackworthltd/primer-app/pull/917#issuecomment-1568207438

My case was slightly different: add an explicit all-way `match` on a subject of a simple sum type, select the `match` node, then start deleting branches. No "add branch" is offered until I select something else and then re-select the `match` node.

**Comment by dhess** [comment]
The bug is annoying, but not a show-stopped, since it can be worked around. As we're currently short on time, I vote we merge this and return to it post-Zurihac.

**Comment by dhess** [comment]
Note to self: merge #955 before this one.

**Review by georgefst — APPROVED** [review]
I mostly share @dhess' UX concerns, but I think this approach works nicely enough for now.

**Pull request merged**
